module Input where

import           Data.List            (groupBy)
import           Data.Vector          (fromList)
import           Model                (Alignment (..), Protein (..))
import           MultipleSeqAlignment (scoreProteins)

mkAl :: [String] -> Alignment
mkAl input = Alignment seqs (scoreProteins seqs)
  where
    seqs = map mkSeq input
    mkSeq str = Protein (aa str) (gps str) (1 / seed)
    seed =
      if denominator == 0
        then 1
        else numerator / denominator
    numerator = fromIntegral (sum (map snd (concatMap gps input)))
    denominator = fromIntegral (length (concatMap gps input))
    aa = fromList . filter (not . isGap)
    gps = go 0 [] . groupBy (\a b -> isGap a && isGap b)
    isGap = (==) '-'
    go i acc (x:xs) =
      go
        (if isGap (head x)
           then i
           else i + 1)
        (if isGap (head x) && not (null xs)
           then (i, length x) : acc
           else acc)
        xs
    go _ acc [] = acc

simpl = mkAl ["KMMEE", "----MM"]

inp = mkAl [aa1, aa2, aa3, aa4]

aa1 =
  "MASKRIPLVAGNWKMNFDHLEATYFVQKLVWLLRDAHFDFKRCEVALFPSFTSLRSVQVLVE-ADKLHVAYGAQSVSVTTQGAFTGDVSADMIAHLGCSYVIVGHSERRKYHPEDDANIVDQVRAVLAAGMQPILCVGESFEERRQGIELDFAVGQVRDVTRDLNEEQAAKLIVAYEPVWAIGTGMVATPQSAQDAANAIRNDLKTTFGTKVSDSVRILYGGSVTSKNAAELISQPDVDGFLIGGAALDVEELAKIARLALKSTKSRN"

aa2 =
  "---MRTRYLIGNWKTNKNLKDAVSFVEQFQQN----KLN-YNAKIGIAPVYVHLTE----IKKIISDSLLLFAQDANFIESGSYTGTVSFTQLQDIGVNNSIIGHSERRKYYNETSAVINQKLFACLKASMQVVLCIGEALGQEIS-----FLKTDLTNCLDTIDKSLIKNLVIAYEPLWAIGTGKTATPEVANQTIKTIREYINDLYDENVANNISILYGGSVDHNNIQKLAIMEQIDGFLVGKASLEIKNFLEMARVYA-------"

aa3 =
  "----RKYFVAANWKCNGTLESIKSLTNSFNNL----DFDPSKLDVVVFPVSVHYDHTR----KLLQSKFSTGIQNVSKFGNGSYTGEVSAEIAKDLNIEYVIIGHFERRKYFHETDEDVREKLQASLKNNLKAVVCFGESLEQREQNKTIEVITKQVKAFVDL--IDNFDNVILVYEPLWAIGTGKTATPEQAQLVHKEIRKIVKDTCGEKQANQIRILYGGSVNTENCSSLIQQEDIDGFLVGNASLKES-FVDIIKSAM-------"

aa4 =
  "-SAKPQPIAAANWKCNGTTASIEKLVQVFNEH----TIS-HDVQCVVAPTFVHIPLVQA---KLRNPKYVISAENA-IAKSGAFTGEVSMPILKDIGVHWVILGHSERRTYYGETDEIVAQKVSEACKQGFMVIACIGETLQQREANQTAKVVLSQTSAIAAKLTKDAWNQVVLAYEPVWAIGTGKVATPEQAQEVHLLLRKWVSENIGTDVAAKLRILYGGSVNAANAATLYAKPDINGFLVGGASLKPE-FRDIIDATR-------"

aa5 =
  "--APRKFFVGGNWKMNGDKKSLGELIQTLNAA----KVP-FTGEIVCAPPEAYLDFARL---K-VDPKFGVAAQNCYKVSKGAFTGEISPAMIKDCGVTWVILGHSERRHVFGESDELIGQKVSHALSEGLGVVACIGEKLDEREAGITEGVVFEVTEVIADD--VKDWSKVVLAYEPVWAIGTGKTASPQQSQELHGKLRKWLKENVSETVADSVRIIYGGSVTGATCKELASEPDVDGFLVGGASLKPE-FVEYKDVRQ-------"

aa6 =
  "MTPGIRPLVAGNWKMNGKGESLTELRAIAAGLSSDL--GRKLDAVICVPATLLS----RAAETLEGETVGLGGQDAHFKTSGAHTGDISPEMLKEAGATHVILGHSERRTDHHESNKLICAKTEAAWAAGLVAIVCVGETASERKAERALDVIGDQLSGSLPDGVT--AENTIIAYEPIWAIGTGLTPTVQDVRAAHAFMREQLIERFGA-KGAHLRLLYGGSVKPSNAAELLGVADVDGALVGGASLKAADFLAICETYRNL-----"

aa7 =
  "--------------MNGNSTSI----KELCSGISQVQYDTSRVAIAVFPSSVY----VKEVISQLPEKVGVGLQNITFYDDGAYTGEISARMLEDIGCDYLLIGHSERRSLFAESDEDVFKKLNKIIDTTITPVVCIGESLDDRKSGKLKQVLATQLSLILENLSVEQLAKVVIAYEPVWAIGTGVVASLEQIQETHQFIRSLLAKVDER-LAKNIKIVYGGSLKAENAKDILSLPDVDGGL--------------------------"

aa8 =
  "--------------MNPMQADAKQLLQEFKQLLQENEITEEKCNIGLAPVTLALTSTQAELANAARSVFTVAQDVSRFGNMGAYTGEVSAELLKDSQIEYVLIGHSERREYFAESAAILNAKAQNALNAGLKVIYCVGESLEQRESGQAEVVVLQQICDLASVVTAEQWPHIVIAYEPIWAIGTGKTASPEDAQTMHAKIREGLTQITSHGA--NMAILYGGSVKAENAVELAACPDINGAL--------------------------"

aa9 =
  "---MRKPIIAGNWKMNKTLSEAVSFVEEVKGQIPAASAV---DAVVCSPALFLE---RLVAA-TEGTDLQVGAQNMHFEKNGAFTGEISPVALSDLKVGYVVLGHSERREMFAETDESVNKKTIAAFEHGLTPIVCCGETLEERESGKTFDLVAGQVTKALAGLTEEQVKATVIAYEPIWAIGTGKSSSSADANEVCAHIRKVVAEVVSPAAAEAVRIQYGGSVKPENIKEYMAQSDIDGALVGGASLEPASFLGLLGAVK-------"

aa10 =
  "--MERKSYVFGNWKMHKTAKEAKDFLSIFCPFVKEISPA---SLVGIAPAFTTLSACCESIK-EMDSSIWLGAQNVHQDSSGAFTGEVSLPMLQEFHVNFVLLGHSECRHIFHEEDATIALKVGAAARSGVVPVLCIGETLEARENGTTKEVLSNQLMLGLAQLPE--TAPVIIAYEPVWAIGTGKVASTADVQEVHAFCREVLSRIFSKEKSEIISILYGGSVKADNAEGFARCPDVDGLLVGGASLDPQGFANVLRNFNL------"
